### PR TITLE
Add cs file reference in physics.md

### PR DESCRIPTION
**Pull request by brutatoasta**

### CODE REVIEW

**Comment by natalieagus** [comment]
Fix the merge conflict first, the collider should use OR and not AND.

**Comment by brutatoasta** [comment]
Sorry for the merge conflict. 
And yes I was about to comment on the boolean operators when testing it 😁

**Comment by natalieagus** [comment]
No worries, the conflict was because of my update that happened right after your PR. 

Hmm can explain what was the unintended behavior? I haven’t tested it because I am using the Layermask method. I will test it tomorrow, brain not working today 😌. 

Btw I found another syntax error cos there’s no enclosing bracket for the if clause (just changed it, so it caused conflict again sorry 😞).

**Comment by brutatoasta** [comment]
[Incorrect mario behavior](https://www.youtube.com/watch?v=KgZ4AmTmDnE)

**Comment by natalieagus** [comment]
Is it possible that that's because the collider is in child component of some GameObject Pipe, but the tag is in the parent? 

I tested the code, [it works as intended.](https://www.dropbox.com/scl/fi/dkn27q4wbkitef7yy7v0f/collider-by-tag.mov?rlkey=fohvdt3r0ivyez1s9xe420eoo&dl=0). You need to put an **and** with the !onGroundState because otherwise it will change mario to be onGroundState when it just collide lets say with the side of the pipe or the obstacle box (instead of the top).

**Comment by brutatoasta** [comment]
OK i will test it later, i think u can close the PR/issue and if theres more problem i can ask in Teams or open an issue. Thanks!

**Comment by brutatoasta** [comment]
> Is it possible that that's because the collider is in child component of some GameObject Pipe, but the tag is in the parent? See demo in the first few seconds of the video below.
> 
> I tested the code, [it works as intended](https://www.dropbox.com/scl/fi/dkn27q4wbkitef7yy7v0f/collider-by-tag.mov?rlkey=fohvdt3r0ivyez1s9xe420eoo&dl=0). You need to put an **and** with the !onGroundState because otherwise it will change mario to be onGroundState when it just collide lets say with the side of the pipe or the obstacle box (instead of the top).

Yes the problem was I didnt tag the children in the prefab as well. Thanks!

**Pull request merged**
